require('plugins')
require('mappings')
require('settings')
require('options')
require('chetan.metals-conf')
require('chetan.nvim-cmp')
require('chetan.telescope')
require('chetan.nvimtree')
require('chetan.lualine')
require('chetan.mason')
require('chetan.nvim-bufferline')
require('chetan.nvim-web-devicons')
require('chetan.rust-tools')
require('chetan.kanagawa')
require('chetan.dap-settings')
-- require('chetan.treesitter')
